<?php
/**
 * EmployeeResponseQuestionnaireTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RetroTax
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Retrotax TCID
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2016-12-19T14:06:08Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RetroTax;

/**
 * EmployeeResponseQuestionnaireTest Class Doc Comment
 *
 * @category    Class */
// * @description EmployeeResponseQuestionnaire
/**
 * @package     RetroTax
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployeeResponseQuestionnaireTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EmployeeResponseQuestionnaire"
     */
    public function testEmployeeResponseQuestionnaire()
    {

    }

    /**
     * Test attribute "afdc"
     */
    public function testPropertyAfdc()
    {

    }

    /**
     * Test attribute "food_stamps"
     */
    public function testPropertyFoodStamps()
    {

    }

    /**
     * Test attribute "ssi"
     */
    public function testPropertySsi()
    {

    }

    /**
     * Test attribute "voc_rehab"
     */
    public function testPropertyVocRehab()
    {

    }

    /**
     * Test attribute "veteran"
     */
    public function testPropertyVeteran()
    {

    }

    /**
     * Test attribute "unemployed"
     */
    public function testPropertyUnemployed()
    {

    }

    /**
     * Test attribute "felon"
     */
    public function testPropertyFelon()
    {

    }

    /**
     * Test attribute "cdib"
     */
    public function testPropertyCdib()
    {

    }

    /**
     * Test attribute "ca_farmer"
     */
    public function testPropertyCaFarmer()
    {

    }

    /**
     * Test attribute "ca_foster"
     */
    public function testPropertyCaFoster()
    {

    }

    /**
     * Test attribute "ca_cal_works"
     */
    public function testPropertyCaCalWorks()
    {

    }

    /**
     * Test attribute "ca_misdemeanor"
     */
    public function testPropertyCaMisdemeanor()
    {

    }

    /**
     * Test attribute "ca_wia"
     */
    public function testPropertyCaWia()
    {

    }

    /**
     * Test attribute "sc_fib"
     */
    public function testPropertyScFib()
    {

    }

}
