<?php
/**
 * EmployeeResponseHiringManagerInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RetroTax
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Retrotax TCID
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2016-12-19T14:06:08Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RetroTax;

/**
 * EmployeeResponseHiringManagerInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description EmployeeResponseHiringManagerInfo
/**
 * @package     RetroTax
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployeeResponseHiringManagerInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "EmployeeResponseHiringManagerInfo"
     */
    public function testEmployeeResponseHiringManagerInfo()
    {

    }

    /**
     * Test attribute "occupation_id"
     */
    public function testPropertyOccupationId()
    {

    }

    /**
     * Test attribute "starting_wage"
     */
    public function testPropertyStartingWage()
    {

    }

    /**
     * Test attribute "dgi"
     */
    public function testPropertyDgi()
    {

    }

    /**
     * Test attribute "dojo"
     */
    public function testPropertyDojo()
    {

    }

    /**
     * Test attribute "doh"
     */
    public function testPropertyDoh()
    {

    }

    /**
     * Test attribute "dsw"
     */
    public function testPropertyDsw()
    {

    }

}
