<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  RetroTax
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Retrotax TCID
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2016-12-19T14:06:08Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace RetroTax;

use \RetroTax\Configuration;
use \RetroTax\ApiClient;
use \RetroTax\ApiException;
use \RetroTax\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  RetroTax
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for applicationStatusesGet
     *
     * .
     *
     */
    public function testApplicationStatusesGet()
    {

    }

    /**
     * Test case for applicationStatusesStatusCodeGet
     *
     * .
     *
     */
    public function testApplicationStatusesStatusCodeGet()
    {

    }

    /**
     * Test case for authenticationDelete
     *
     * .
     *
     */
    public function testAuthenticationDelete()
    {

    }

    /**
     * Test case for authenticationPost
     *
     * .
     *
     */
    public function testAuthenticationPost()
    {

    }

    /**
     * Test case for authenticationUserDetailsGet
     *
     * .
     *
     */
    public function testAuthenticationUserDetailsGet()
    {

    }

    /**
     * Test case for branchesGet
     *
     * .
     *
     */
    public function testBranchesGet()
    {

    }

    /**
     * Test case for companiesCompanyIdGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdGet()
    {

    }

    /**
     * Test case for companiesCompanyIdLocationsGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdLocationsGet()
    {

    }

    /**
     * Test case for companiesCompanyIdLocationsLocationIdGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdLocationsLocationIdGet()
    {

    }

    /**
     * Test case for companiesGet
     *
     * .
     *
     */
    public function testCompaniesGet()
    {

    }

    /**
     * Test case for employeesEmployeeIdDocumentsGet
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdDocumentsGet()
    {

    }

    /**
     * Test case for employeesEmployeeIdDocumentsPost
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdDocumentsPost()
    {

    }

    /**
     * Test case for employeesEmployeeIdEsignPut
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdEsignPut()
    {

    }

    /**
     * Test case for employeesEmployeeIdGet
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdGet()
    {

    }

    /**
     * Test case for employeesEmployeeIdPayEntriesGet
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdPayEntriesGet()
    {

    }

    /**
     * Test case for employeesEmployeeIdPayEntriesPayEntryIdDelete
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdPayEntriesPayEntryIdDelete()
    {

    }

    /**
     * Test case for employeesEmployeeIdPayEntriesPayEntryIdPut
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdPayEntriesPayEntryIdPut()
    {

    }

    /**
     * Test case for employeesEmployeeIdPayEntriesPost
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdPayEntriesPost()
    {

    }

    /**
     * Test case for employeesEmployeeIdPut
     *
     * .
     *
     */
    public function testEmployeesEmployeeIdPut()
    {

    }

    /**
     * Test case for employeesGet
     *
     * .
     *
     */
    public function testEmployeesGet()
    {

    }

    /**
     * Test case for employeesPost
     *
     * .
     *
     */
    public function testEmployeesPost()
    {

    }

    /**
     * Test case for occupationsGet
     *
     * .
     *
     */
    public function testOccupationsGet()
    {

    }

    /**
     * Test case for reportsGet
     *
     * .
     *
     */
    public function testReportsGet()
    {

    }

    /**
     * Test case for statesGet
     *
     * .
     *
     */
    public function testStatesGet()
    {

    }

    /**
     * Test case for statesStateCodeCountiesGet
     *
     * .
     *
     */
    public function testStatesStateCodeCountiesGet()
    {

    }

    /**
     * Test case for subscriptionsGet
     *
     * .
     *
     */
    public function testSubscriptionsGet()
    {

    }

    /**
     * Test case for subscriptionsPost
     *
     * .
     *
     */
    public function testSubscriptionsPost()
    {

    }

    /**
     * Test case for subscriptionsSubscriptionIdDelete
     *
     * .
     *
     */
    public function testSubscriptionsSubscriptionIdDelete()
    {

    }

    /**
     * Test case for subscriptionsSubscriptionIdGet
     *
     * .
     *
     */
    public function testSubscriptionsSubscriptionIdGet()
    {

    }

    /**
     * Test case for subscriptionsSubscriptionIdPut
     *
     * .
     *
     */
    public function testSubscriptionsSubscriptionIdPut()
    {

    }

    /**
     * Test case for subscriptionsTypesGet
     *
     * .
     *
     */
    public function testSubscriptionsTypesGet()
    {

    }

    /**
     * Test case for supplementaryProgramStatusesGet
     *
     * .
     *
     */
    public function testSupplementaryProgramStatusesGet()
    {

    }

    /**
     * Test case for supplementaryProgramStatusesStatusCodeGet
     *
     * .
     *
     */
    public function testSupplementaryProgramStatusesStatusCodeGet()
    {

    }

    /**
     * Test case for supplementaryProgramsGet
     *
     * .
     *
     */
    public function testSupplementaryProgramsGet()
    {

    }

    /**
     * Test case for supplementaryProgramsSupplementaryProgramCodeGet
     *
     * .
     *
     */
    public function testSupplementaryProgramsSupplementaryProgramCodeGet()
    {

    }

    /**
     * Test case for targetGroupsGet
     *
     * .
     *
     */
    public function testTargetGroupsGet()
    {

    }

    /**
     * Test case for targetGroupsTargetGroupCodeGet
     *
     * .
     *
     */
    public function testTargetGroupsTargetGroupCodeGet()
    {

    }

    /**
     * Test case for usersChangePasswordPut
     *
     * .
     *
     */
    public function testUsersChangePasswordPut()
    {

    }

    /**
     * Test case for usersForgotPasswordPost
     *
     * .
     *
     */
    public function testUsersForgotPasswordPost()
    {

    }

    /**
     * Test case for usersForgotUsernamePost
     *
     * .
     *
     */
    public function testUsersForgotUsernamePost()
    {

    }

    /**
     * Test case for usersPut
     *
     * .
     *
     */
    public function testUsersPut()
    {

    }

    /**
     * Test case for zoneStatusesGet
     *
     * .
     *
     */
    public function testZoneStatusesGet()
    {

    }

    /**
     * Test case for zoneStatusesStatusCodeGet
     *
     * .
     *
     */
    public function testZoneStatusesStatusCodeGet()
    {

    }

    /**
     * Test case for zonesGet
     *
     * .
     *
     */
    public function testZonesGet()
    {

    }

    /**
     * Test case for zonesZoneCodeGet
     *
     * .
     *
     */
    public function testZonesZoneCodeGet()
    {

    }

}
